sudo: required
language: node_js
node_js: "8"

script: skip

jobs:
  include:
    - stage: Tests
      script: echo "No tests at the moment"

    - stage: Build and push image
      services:
        - docker
      install: skip
      before_script:
        - docker build -t rupaya/stats .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag rupaya/stats rupaya/stats:latest
        - docker push rupaya/stats:latest
        - docker tag rupaya/stats rupaya/stats:$TRAVIS_BUILD_ID
        - docker push rupaya/stats:$TRAVIS_BUILD_ID

    - stage: Build and push image (tagged)
      services:
        - docker
      install: skip
      before_script:
        - docker build -t rupaya/stats .
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag rupaya/stats rupaya/stats:latest
        - docker push rupaya/stats:latest
        - docker tag rupaya/stats rupaya/stats:testnet
        - docker push rupaya/stats:testnet
        - docker tag rupaya/stats rupaya/stats:$TRAVIS_TAG
        - docker push rupaya/stats:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Tests
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = rupaya/stats
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = rupaya/stats
